### ISSUE TITLE
Grunt less:theme - NameError: variable @media-common is undefined

### ISSUE THREAD

**Issue by phillipmeyer** [studioemma/magento2-theme-optimus#1]
When I try and pass this theme through grunt it fails with the following error:

```
>> NameError: variable @media-common is undefined in pub/static/frontend/vendor/theme/en_GB/css/source/_optimus-lib.less on line 6, column 9:
>> 5 
>> 6 & when (@media-common = true) {
>> 7
Warning: Error compiling pub/static/frontend/vendor/theme/en_GB/css/_optimus.less Use --force to continue.

Aborted due to warnings.
```

**Comment by debuysserk** [comment]
Hi philip,

Can you give us some more info on the way your project is setup? How is the theme structure, what is the command you were trying to run?

Thanks

**Comment by phillipmeyer** [comment]
Hi,

Thank you so much for coming back to me on this. I managed make Grunt to work this morning by adding the following code to the top of your file css/source/_optimus-lib.less but I'm not sure why it's not picking up the relevant information anyway.

```
@import (reference) "../source/lib/variables/_responsive.less";
@import (reference) "../source/lib/_responsive.less";
```

I'm using a fairly fresh install of Magento 2.1.6 with php 7, with absolutely no extensions or changes installed. I installed optimus exactly as described in the readme and grunt works perfectly on the Magento/blank theme without any changes.

I have tried using grunt directly on your theme and also my theme (which uses yours as a parent). For the sake of simplicity, here is my themes.js file that only currently has my theme showing. I'm fairly sure that my theme is configured correctly but it's possible that I have not configured this file correctly as I'm very new to grunt. (For info, I have tried changing locale to en_US too). The grunt files in the Magento route folder are unchanged as the sample files.

```
   theme: {
        area: 'frontend',
        name: 'vendor/theme',
        locale: 'en_GB',
        files: [
            'css/styles-m',
            'css/styles-l',
            'css/email',
            'css/email-inline',
            'css/_optimus',
            'css/email-inline',
            'css/email',
            'css/optimus-l',
            'css/optimus-m',
            'css/print',
            'css/source/_extend'
        ],
        dsl: 'less'
    }
```

**Comment by debuysserk** [comment]
Hi Phillip,

I'm seeing some extra lines in your grunt config & the order isn't how it's supposed to be. _optimus for instance & twice the email lines etc + _extend shouldn't be there.

I've noticed there's no readme on the grunt config so we'll add that to the readme file in the repo.

For now, here's our grunt config for a client theme : 

    {{themename}}: {
        area: 'frontend',
        name: '{{themepackage}}/{{themefolder}}',
        locale: 'en_US',
        files: [
            'css/optimus-m',
            'css/optimus-l',
            'css/styles-m',
            'css/styles-l',
            'css/print',
            'css/email',
            'css/email-inline'
        ],
        dsl: 'less'


Let us know how this goes and we'll update the readme.md.

Thanks!

**Comment by Quinten** [comment]
Hi Phillip,

also don't forget to run bin/magento with the following arguments:

            bin/magento dev:source-theme:deploy --theme=vendor/theme --locale=en_US css/styles-m css/optimus-m css/styles-l css/optimus-l css/print 

where 'vendor/theme' will be your vendor and theme folder names. Do this before you run `grunt watch`. This way you won't need those extra import statements.

**Comment by debuysserk** [comment]
FYI : the readme file has been updated with the Grunt configs.

**Comment by phillipmeyer** [comment]
Hi, your config worked perfectly, it was just my inexperience with grunt. Sorry to have troubled you with it and thank you so much for helping!

One last question, should I include my own 'css/source/_extend' file in the above file or will it get picked up automatically?

**Comment by debuysserk** [comment]
Glad it worked!

No, your _extend fille will be automatically included in styles-m/l when grunt watch is running. But you will have to re-run the source-theme commend to add a symlink to the _extend.less file after you've added it. Grunt watch will not be able to see it until you've done that.
