### ISSUE TITLE
var/www/test.com/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93

### ISSUE THREAD

**Issue by patrickouc** [studioemma/magento2-theme-optimus#3]
hello, I installed this theme some error,
The default luma theme is OK。

PHP 7.0.19
nginx 1.13

`Fatal error: Uncaught Error: Class 'StudioEmma\Core\Helper\Store' not found in /var/www/test.com/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93 Stack trace: #0 /var/www/test.com/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('StudioEmma\\Core...', Array) #1 /var/www/test.com/html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('StudioEmma\\Core...') #2 /var/www/test.com/html/vendor/magento/framework/View/TemplateEngine/Php.php(122): Magento\Framework\ObjectManager\ObjectManager->get('StudioEmma\\Core...') #3 /var/www/test.com/html/app/design/frontend/Studioemma/optimus/Magento_Theme/templates/html/opengraph/general.phtml(3): Magento\Framework\View\TemplateEngine\Php->helper('StudioEmma\\Core...') #4 /var/www/test.com/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/test.c...') #5 /var/www/test.com/html in /var/www/test.com/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93`

**Comment by Quinten** [comment]
Did you install it with composer?

You also need to add studioemma/magento2-module-core and studioemma/magento2-module-optimus as dependencies. See https://github.com/studioemma/magento2-theme-optimus/blob/master/composer.json

Best to follow the intructions in the readme. It outlines how to install the theme with composer.

**Comment by patrickouc** [comment]
thank you , I use composer it's ok.
